version: '3.8'

services:

  postgres:
    image: postgres:17
    container_name: wallet-postgres
    environment:
      POSTGRES_DB: wallet_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: wallet-redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: wallet-app
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - redis